import { Member } from "./types";
import jsm from "./profile/jsm.png";
import kjw from "./profile/kjw.gif";
import idy from "./profile/idy.png";
import knh from "./profile/knh.png";
import btw from "./profile/btw.png";
import ide from "./profile/ide.png";
import jsy from "./profile/jsy.png";

export const members: Member[] = [
  {
    id: 1,
    name: "정소민",
    role: "Frontend",
    intro: "컴퓨터공학과 25학번 정소민입니다.",
    image: jsm,
    badge: "React",
    club: "디스이즈",
    bio: "컴퓨터공학과 25학번 정소민입니다. 프론트엔드를 맡고 있습니다.",
    email: "sominjung1116@gmail.com",
    phone: "010-5615-8474",
    website: "https://www.instagram.com/__z1siim",
    skills: ["React", "ReactNative", "JavaScript"],
    motto: "열심히 하겠습니다.",
    isMe: true,
  },
  {
    id: 2,
    name: "김주완",
    role: "Frontend",
    intro: "성실히 배우고 싶은 학생입니다.",
    image: kjw,
    badge: "HTML/CSS",
    club: "LikeLion DAU",
    bio: "컴퓨터공학과 1학년입니다. 웹 개발을 배우며, 코드 하나하나 다 이해하려고 노력하고 있습니다.",
    email: "mmnnbbnn070910@gmail.com",
    phone: "010-9041-1287",
    website: "https://likelion.net/",
    skills: ["HTML/CSS", "JavaScript", "React(학습 중)"],
    motto: "성실히 배워서 웹개발 마스터가 되고 싶습니다.",
  },
  {
    id: 3,
    name: "임도영",
    role: "Frontend",
    intro: "아기사자 14기 프론트엔드 임도영입니다.",
    image: idy,
    badge: "HTML / CSS",
    club: "디스이즈",
    bio: "동아대 26학번 컴퓨터공학과, 아기사자 14기 임도영입니다. 이번 활동을 통해 많이 공부하며, 공부한 것을 활동 및 대회 참여를 통해 활용해나가며 경험과 기술을 쌓기 위해 노력하겠습니다. 앞으로 잘 부탁드립니다.",
    email: "dlaehdud342@naver.com",
    phone: "010-3516-6306",
    website: "https://www.google.com",
    skills: ["HTML / CSS", "JavaScript", "React", "JAVA", "C / C++"],
    motto: "꾸준히 노력하고 적극적인 참여를 통해 성장하는 개발자가 되겠습니다.",
  },
  {
    id: 4,
    name: "김나함",
    role: "Frontend",
    intro: "분야를 넘나들며 성장하는 개발자입니다.",
    image: knh,
    badge: "HTML / CSS",
    club: "멋쟁이사자처럼 아기사자 14기, 자기개발 동아리",
    bio: "동아대학교 응용생물공학과 25학번 김나함입니다. 멋쟁이사자처럼을 통해 처음 프론트엔드에 도전하는 중입니다.",
    email: "naham9488@gmail.com",
    phone: "010-3626-9488",
    website: "",
    skills: ["HTML / CSS", "JavaScript"],
    motto: "부족한 점은 많지만 포기하지 않고 계속 노력하여 성장하는 아기사자가 되겠습니다!",
  },
  {
    id: 5,
    name: "백태우",
    role: "Frontend",
    intro: "I'm Empty Stack Junior",
    image: btw,
    badge: "NLU / NLG",
    club: "DAU_DSIS",
    bio: "AI학과이지만 Full Stack Developer를 목표로 하고있기 때문에 Frontend에서 짱 먹어보겠습니다 감사합니다",
    email: "btu0414@gmail.com",
    phone: "010-4564-4725",
    website: "https://www.acmicpc.net/",
    skills: ["NLU / NLG", "NLP", "LLM"],
    motto: "모두가 원하는 개발자가 되어보겠습니다.",
  },
  {
    id: 6,
    name: "이도은",
    role: "Frontend",
    intro: "열심히 배우는 프론트엔드 개발자입니다!",
    image: ide,
    badge: "HTML / CSS",
    club: "LION TRACK",
    bio: "모르는게 너무 많은 말하는수국입니다. 스펀지처럼 이해하려고 노력하고 있습니다. 배움에는 끝이없다..!",
    email: "dodo55860@gmail.com",
    phone: "010-2686-5586",
    website: "",
    skills: ["HTML / CSS", "JavaScript", "React (학습 중)"],
    motto: "팀원들에게 든든한 개발자가 되고싶습니다.",
  },
  {
    id: 7,
    name: "정서윤",
    role: "Frontend",
    intro: "열심히 배워가고있는 프론트엔드 개발자입니다!",
    image: jsy,
    badge: "TypeScript",
    club: "디스이즈",
    bio: "안녕하세요, 프론트엔드를 맡고 있는 07년생 26학번 컴퓨터공학과 정서윤입니다. 아직 부족한 점이 많지만, 배우는 과정 자체를 즐기며 꾸준히 성장하고 있습니다. MBTI는 ESTP이고, 이번 멋사 리그에는 '쫄?'이라는 게임으로 참여했습니다.",
    email: "t01021124995@gmail.com",
    phone: "010-3846-5638",
    website: "https://github.com/dkjksd",
    skills: [
      "TypeScript — 타입 기반 개발",
      "SSR/SSG — 서버 사이드 렌더링",
      "Utility-First CSS — 효율적인 스타일링",
      "Server State Management — 데이터 관리 최적화",
    ],
    motto: "기초를 탄탄히 다지며, 맡은 역할을 끝까지 책임지는 개발자가 되겠습니다.",
  },
];