import doeun from "../../assets/juwan/doeun.jpeg";
import doyoung from "../../assets/juwan/doyoung.jpg";
import somin from "../../assets/juwan/somin.png";
import juwan from "../../assets/juwan/juwan.gif";
import naham from "../../assets/juwan/naham.png";
import seoyun from "../../assets/juwan/seoyun.png";
import taewoo from "../../assets/juwan/taewoo.jpg";
import taeyeop from "../../assets/juwan/taeyeop.png";
import type { Member } from "./types";

// Member[] 명시로 배열 안에 잘못된 구조(필드 누락, 타입 불일치)가 들어가면
// 컴파일 타임에 잡힌다. 가령 role을 "front"로 적으면 Role 유니온에 없어서 에러.
export const members: Member[] = [
  {
    name: "김주완",
    role: "Frontend",
    intro: "성실히 배우고 싶은 학생입니다.",
    description: "웹 개발을 배우며 프론트엔드 개발자로 성장하고 싶은 학생입니다.",
    image: juwan,
    badge: "React",
    isMe: true,
    club: "LION TRACK",
    email: "mmnnbbnn070910@gmail.com",
    phone: "010-9041-1287",
    website: "https://likelion.net/",
    comment: "성실히 배워서 웹개발 마스터가 되고 싶습니다.",
  },
  {
    name: "임도영",
    role: "Frontend",
    intro: "아기사자 14기 프론트엔드 임도영입니다.",
    description: "프론트엔드 개발을 배우며 꾸준히 성장하고 싶은 아기사자입니다.",
    image: doyoung,
    badge: "React",
    club: "LION TRACK",
    email: "dlaehdud342@naver.com",
    phone: "010-3516-6306",
    website: "https://www.google.com",
    comment: "꾸준히 노력하고 적극적인 참여를 통해 성장하는 개발자가 되겠습니다.",
  },
  {
    name: "김나함",
    role: "Frontend",
    intro: "분야를 넘나들며 성장하는 개발자입니다.",
    description: "다양한 분야에 관심을 가지고 배우며 성장하는 프론트엔드 개발자입니다.",
    image: naham,
    badge: "JavaScript",
    club: "LION TRACK",
    email: "naham9488@gmail.com",
    phone: "010-3626-9488",
    website: "https://instagram.com/kim_naham",
    comment: "부족한 점은 많지만 포기하지 않고 계속 노력하여 성장하는 아기사자가 되겠습니다!",
  },
  {
    name: "백태우",
    role: "Frontend",
    intro: "I'm Empty Stack Junior :(",
    description: "아직은 Empty Stack이지만 꾸준히 배워 성장하고 싶은 개발자입니다.",
    image: taewoo,
    badge: "AI/NLP",
    club: "LION TRACK",
    email: "btu0414@gmail.com",
    phone: "010-4564-4725",
    website: "https://www.acmicpc.net",
    comment: "모두가 원하는 개발자가 되어보겠습니다.",
  },
  {
    name: "정소민",
    role: "Frontend",
    intro: "컴퓨터공학과 25학번 정소민입니다.",
    description: "컴퓨터공학을 전공하며 프론트엔드와 앱 개발에 관심을 가지고 있습니다.",
    image: somin,
    badge: "React Native",
    club: "LION TRACK",
    email: "sominjung1116@gmail.com",
    phone: "010-5615-8474",
    website: "https://www.instagram.com/__z1siim",
    comment: "열심히 하겠습니다.",
  },
  {
    name: "이도은",
    role: "Frontend",
    intro: "열심히 배우는 프론트엔드 개발자입니다!",
    description: "프론트엔드를 배우며 팀원들에게 도움이 되는 개발자가 되고 싶습니다.",
    image: doeun,
    badge: "React",
    club: "LION TRACK",
    email: "dodo55860@gmail.com",
    phone: "010-2686-5586",
    website: "",
    comment: "팀원들에게 도움이 되는 개발자가 되고 싶습니다.",
  },
  {
    name: "정서윤",
    role: "Frontend",
    intro: "준비중...",
    description: "현재 자기소개를 준비하고 있습니다.",
    image: seoyun,
    badge: "HTML/CSS",
    club: "LION TRACK",
    email: "example@gmail.com",
    phone: "010-1234-5678",
    website: "https://example.com",
    comment: "준비중...",
  },
  {
    name: "이태엽",
    role: "Frontend",
    intro: "준비중...",
    description: "현재 자기소개를 준비하고 있습니다.",
    image: taeyeop,
    badge: "TypeScript",
    club: "LION TRACK",
    email: "example@gmail.com",
    phone: "010-1234-5678",
    website: "https://example.com",
    comment: "준비중...",
  },
];
